[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A client library for CoreOS's etcd."
documentation = "http://jimmycuadra.github.io/rust-etcd/etcd/"
homepage = "https://github.com/jimmycuadra/rust-etcd"
keywords = ["etcd", "coreos", "database"]
license = "MIT"
name = "etcd"
readme = "README.md"
repository = "https://github.com/jimmycuadra/rust-etcd"
version = "0.5.5"

[dependencies]
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
url = "1.4.0"

[dev-dependencies]
native-tls = "0.1.2"
