[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
build = "build.rs"
description = "A client library for CoreOS's etcd."
documentation = "http://jimmycuadra.github.io/rust-etcd/etcd/"
homepage = "https://github.com/jimmycuadra/rust-etcd"
keywords = ["etcd", "coreos", "database"]
license = "MIT"
name = "etcd"
readme = "README.md"
repository = "https://github.com/jimmycuadra/rust-etcd"
version = "0.2.0"

[build-dependencies]
serde_codegen = "0.6.11"
syntex = "0.26.0"

[dependencies]
hyper = "0.7.2"
serde = "0.6.11"
serde_json = "0.6.0"
url = "0.5.3"

[lib]
doctest = false
name = "etcd"
