[package]

name = "etcd"
version = "0.1.0"
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A client library for CoreOS's etcd."
license = "MIT"
readme = "README.md"
keywords = ["etcd", "coreos", "database"]
repository = "https://github.com/jimmycuadra/rust-etcd"
homepage = "https://github.com/jimmycuadra/rust-etcd"

[lib]

name = "etcd"
doctest = false

[dependencies]

hyper = ">= 0.3.15"
rustc-serialize = ">= 0.3.14"
url = ">= 0.2.31"
