[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
build = "build.rs"
description = "A client library for CoreOS's etcd."
documentation = "http://jimmycuadra.github.io/rust-etcd/etcd/"
homepage = "https://github.com/jimmycuadra/rust-etcd"
keywords = ["etcd", "coreos", "database"]
license = "MIT"
name = "etcd"
readme = "README.md"
repository = "https://github.com/jimmycuadra/rust-etcd"
version = "0.5.1"

[build-dependencies]
syntex = "0.31.0"

[build-dependencies.serde_codegen]
optional = true
version = "0.7.2"

[dependencies]
hyper = "0.8.1"
openssl = "0.7.9"
serde = "0.7.0"
serde_json = "0.7.0"
url = "0.5.9"

[dependencies.serde_macros]
optional = true
version = "0.7.2"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
